### ISSUE TITLE
nightly-trunk?

### ISSUE THREAD

**Issue by plepe** [mapnik/mapnik-packaging#170]
Shouldn't  the nightly packages on ppa.launchpad.net be updated regularly (like every night or so)? Because most of the packages in http://ppa.launchpad.net/mapnik/nightly-trunk/ubuntu/pool/main/m/mapnik/ are pretty old. The packages for Trusty Thar (14.04 LTS) date from 2014, May 20; the packages for Precise Pangolin (12.04 LTS) even from 2014, April 25, which was before branch expr-v2 (mapnik/mapnik#2222) was merged.

Thanks in advance!

**Comment by springmeyer** [comment]
closing, nightly-trunk is building great now https://launchpad.net/~mapnik/+archive/ubuntu/nightly-trunk/+packages thanks to help from @pnorman and @rcoup. And we're tracking any remaining issues over at https://github.com/mapnik/debian/issues
