### ISSUE TITLE
Building for IOS 64

### ISSUE THREAD

**Issue by HS95518** [mapnik/mapnik-packaging#187]
We need mapnik to support IOS armv7, arm64, i386 and x86-64. How can we build it for arm64 and x86-64?

**Comment by springmeyer** [comment]
Why do you need to build Mapnik for iOS? Could you use some other map renderer designed for iOS like  https://github.com/mapbox/mapbox-gl-native?

**Comment by HS95518** [comment]
We are using Mapnik to load map data. It is working properly but in the near future apple store requires all applications built for 64bit, so we need to compile it for arm64 and x86_64, i.e. the dependent libraries used by Mapnik.

[cid:image001.png@01D0565A.FFD57910]<http://www.navtech.aero/>Hongwei Shen | Senior Software Developer - APS | hshen@navtech.aero<mailto:hshen@navtech.aero> | Phone: 519-747-1170 x 297 | skype: hongwei.shen | visit us at www.navtech.aero<http://www.navtech.aero>

**Comment by springmeyer** [comment]
@HS95518 You can try this by doing:

```sh
git clone https://github.com/mapnik/mapnik-packaging.git
cd mapnik-packaging
export CXX11=true
export MASON_PLATFORM=iPhoneOS64
source build.sh
build_mapnik
```

However it has been a while since I tested iOS builds so there are likely a few things broken. I currently only use these scripts to target `x86_64` on OS X and Linux.

**Comment by HS95518** [comment]
Thanks. We have mapnik source code in xcode project. What we really need to do is to compile all the libs that mapnik depends on for arm64, x86_64, i386 and armv7. It took me a few days and I was able to buil them all successfully. Mission completed!

**Comment by springmeyer** [comment]
@HS95518 sure, how did you compile them?

**Comment by HS95518** [comment]
Script here for boost: https://github.com/danoli3/ofxiOSBoost
Make file here with modifications for spatialite: https://github.com/gstf/libspatialite-ios
Script here with modifications to build other libs: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src

**Comment by HS95518** [comment]
And Script with modifications for ICU from here: https://github.com/zhm/icu-ios

**Comment by dhthong92** [comment]
How about lib Harfbuzz? I haved followed your instruction and it worked well except Harfbuzz deps. It didn't have prebuilt lib or any way to build for armv7 or i386, only have for x85_64. Any idea?

**Comment by HS95518** [comment]
I think harbuzz has compil error when build for ios, It is in file jpeg_io.hpp, "fale" should be changed to "FALSE", "1" and "true" should be changed to "TRUE" in 4 places.

**Comment by dhthong92** [comment]
Is this what you say to?
https://github.com/mapnik/mapnik/commit/860631acc5605a1ab6bdec59850dd233cbfe1a4f
It seem has been fixed. But this is mapnik sources, I don't see anything link with harfbuzz. Could you explain more? Many thanks

**Comment by HS95518** [comment]
Ya, that is what I was talking about. I didn't encounter any other issue while building harfbuzz inside mapnik.

**Comment by dhthong92** [comment]
I also build harfbuzz successfully, but it only supports x86_64 architecture. To run in iOS, it need to support armv7 and i386 too. That's what I can't solved. Each of deps which you have gave in previous comments support armv7, arm64, i386 and x86_64 well, only harfbuzz not. That's what I mean

**Comment by HS95518** [comment]
Ok, we put mapnik and harfbuzz in a xcode project to build them for all architectures. I am pretty sure if you can build it for x86_64, you should be able to build it for other architectures. It should be setting in config file if you do not use xcode.

**Comment by dhthong92** [comment]
Arggggg, I've just compiled it from command line, follow instruction in its github, also try this http://lists.freedesktop.org/archives/harfbuzz/2012-August/002414.html but still cant compile, not think about put it in a xcode project. Ok, I will try to build it by using xcode. Many thanks for your help!

**Comment by minikin** [comment]
@HS95518 Could you explain ,please, how did you compile mapnik & harfbuzz  with Xcode?

**Comment by minikin** [comment]
@springmeyer Dane, this method doesn't work : 
`
git clone https://github.com/mapnik/mapnik-packaging.git
cd mapnik-packaging
export CXX11=true
export MASON_PLATFORM=iPhoneOS64
source build.sh
build_mapnik
`
and I can't fix it.

**Comment by springmeyer** [comment]
@minikin these scripts are no longer maintained for iOS. If you are looking for a renderer for maps on iOS take a look at https://github.com/mapbox/mapbox-gl-native
