### ISSUE TITLE
64 bits build on Windows

### ISSUE THREAD

**Issue by cboittin** [mapnik/mapnik-packaging#188]
I need mapnik embedded in a 64 bits Python 2.7 on Windows, so i'm trying to build it from source using VS2008 compiler.

I got all the dependencies compiled in 64bits.
However, when compiling mapnik, i get this error :
```
c:\users\cboittin\downloads\mapnik-2.3.x\plugins\input\shape\shapefile.hpp(162) : 
error C2664: 'std::basic_ifstream<_Elem,_Traits>::basic_ifstream(const char *,std::ios_base::openmode,int)' :
 cannot convert parameter 1 of 'std::wstring' to 'const char *'
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>
        ]
       No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

The same error happens in a few other files.
I also get unresolved externals with boost and mapnik at the linking phase, but i'm not sure if and how these are related.

Any help would be much appreciated.

**Comment by BergWerkGIS** [comment]
@cboittin 

I cannot help you with the error, maybe @springmeyer can chime in.

But if you want to take a look at the latest mapnik 3 RC1, here's a 64bit build:
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-645-gfe01d52.7z

It has been built with Visual Studio 2014 CTP4 (C++11), so you also need the corresponding runtime, if you don't have it already:
https://mapnik.s3.amazonaws.com/dist/dev/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64.exe

**Comment by springmeyer** [comment]
I've never attempted to compile Mapnik 2.3.x or 3.x with VS2008, so I'm not surprised there are problems. My recommendation would be to use VS 2010 if trying to build Mapnik 2.3.x (and then source compile python with 2010) or just move to Mapnik 3.x and use VS 2014 as @BergWerkGIS  is doing over at https://github.com/mapbox/windows-builds
