### ISSUE TITLE
Error during mapnik compilation on Win7

### ISSUE THREAD

**Issue by maraev** [mapnik/mapnik-packaging#192]
Thanks for sollution !
I'm trying to compile mapnik for windows and I'm stuck on compling ICU library. When I start
 bash ./runConfigureICU Cygwin/MSVC --prefix=%ROOTDIR%\icu
I get this:
export CPP= CC=cl CXX=cl CPPFLAGS= CFLAGS= /Gy /MD CXXFLAGS= /Gy /MD LDFLAGS= MAKE=
Running ./configure  --prefix=c:\dev2\icu for Windows with Cygwin using Microsoft Visual C++ compiler

checking for ICU version numbers... release 4.8.1.1, library 48.1.1, unicode version 6.0
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking target system type... i686-pc-mingw32
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking for gcc... cl
checking whether the C compiler works... no
configure: error: in `/c/dev2/icu/source':
configure: error: C compiler cannot create executables
See `config.log' for more details
./runConfigureICU: ./configure failed

What am I doing wrong?

**Comment by maraev** [comment]
my config.log>>>
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.67.  Invocation command line was

  $ ./configure --prefix=c:\dev2\icu

## --------- ##
## Platform. ##
## --------- ##

hostname = WS-1882
uname -m = i686
uname -r = 1.0.12(0.46/3/2)
uname -s = MINGW32_NT-6.1
uname -v = 2012-07-05 14:56

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /c/Python27/Scripts
PATH: /c/Python27
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/VC/BIN
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/Tools
PATH: /c/windows/Microsoft.NET/Framework/v3.5
PATH: /c/windows/Microsoft.NET/Framework/v2.0.50727
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/VC/VCPackages
PATH: /c/Program Files/Microsoft SDKs/Windows/v6.0A/bin
PATH: /c/ProgramData/Oracle/Java/javapath
PATH: /c/APP/ACCESS_USER/PRODUCT/11.2.0/CLIENT_1/BIN
PATH: /c/ORACLE/PRODUCT/10.2.0/CLIENT_1/BIN
PATH: /c/windows/SYSTEM32
PATH: /c/windows
PATH: /c/windows/SYSTEM32/WBEM
PATH: /c/windows/SYSTEM32/WINDOWSPOWERSHELL/V1.0/
PATH: /c/PROGRAM FILES/INTEL/DMIX
PATH: /c/PROGRAM FILES/INTEL/WIFI/BIN/
PATH: /c/PROGRAM FILES/COMMON FILES/INTEL/WIRELESSCOMMON/
PATH: /c/Program Files/ThinkPad/Bluetooth Software/
PATH: /c/Program Files/ThinkPad/Bluetooth Software/syswow64
PATH: /c/Program Files/OpenVPN/bin
PATH: /c/Program Files (x86)/Skype/Phone/
PATH: /c/Program Files (x86)/Google/Chrome/Application
PATH: /c/ProgramData/Oracle/Java/javapath
PATH: /c/APP/ACCESS_USER/PRODUCT/11.2.0/CLIENT_1/BIN
PATH: /c/ORACLE/PRODUCT/10.2.0/CLIENT_1/BIN
PATH: /c/windows/SYSTEM32
PATH: /c/windows
PATH: /c/windows/SYSTEM32/WBEM
PATH: /c/windows/SYSTEM32/WINDOWSPOWERSHELL/V1.0/
PATH: /c/PROGRAM FILES/INTEL/DMIX
PATH: /c/PROGRAM FILES/INTEL/WIFI/BIN/
PATH: /c/PROGRAM FILES/COMMON FILES/INTEL/WIRELESSCOMMON/
PATH: /c/Program Files/ThinkPad/Bluetooth Software/
PATH: /c/Program Files/ThinkPad/Bluetooth Software/syswow64
PATH: /c/Program Files/OpenVPN/bin
PATH: /c/Program Files (x86)/Skype/Phone/
PATH: /usr/bin
PATH: /c/cygwin/bin
PATH: /c/GnuWin32/bin
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/VC/BIN
PATH: .
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/Tools
PATH: /c/windows/Microsoft.NET/Framework/v3.5
PATH: /c/windows/Microsoft.NET/Framework/v2.0.50727
PATH: /c/Program Files (x86)/Microsoft Visual Studio 9.0/VC/VCPackages
PATH: /c/Program Files/Microsoft SDKs/Windows/v6.0A/bin
PATH: .


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2577: checking for ICU version numbers
configure:2609: result: release 4.8.1.1, library 48.1.1, unicode version 6.0
configure:2648: checking build system type
configure:2662: result: i686-pc-mingw32
configure:2682: checking host system type
configure:2695: result: i686-pc-mingw32
configure:2715: checking target system type
configure:2728: result: i686-pc-mingw32
configure:2763: checking whether to build debug libraries
configure:2775: result: no
configure:2780: checking whether to build release libraries
configure:2792: result: yes
configure:2849: checking for gcc
configure:2876: result: cl
configure:3105: checking for C compiler version
configure:3114: cl --version >&5
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
configure:3125: $? = 2
configure:3114: cl -v >&5
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-v'
cl : Command line error D8003 : missing source filename
configure:3125: $? = 2
configure:3114: cl -V >&5
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8004 : '/V' requires an argument
configure:3125: $? = 2
configure:3114: cl -qversion >&5
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-qversion'
cl : Command line error D8003 : missing source filename
configure:3125: $? = 2
configure:3145: checking whether the C compiler works
configure:3167: cl  /Gy /MD   conftest.c  >&5
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9024 : unrecognized source file type 'c:/git/Gy', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'c:/git/MD', object file assumed
conftest.c
Microsoft (R) Incremental Linker Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:Gy.exe 
c:/git/Gy 
c:/git/MD 
conftest.obj 
LINK : fatal error LNK1181: cannot open input file 'c:/git/Gy.obj'
configure:3171: $? = 2
configure:3209: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3214: error: in `/c/dev2/icu/source':
configure:3216: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=i686-pc-mingw32
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value=cl
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=' /Gy /MD'
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=cl
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value=' /Gy /MD'
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=i686-pc-mingw32
ac_cv_prog_ac_ct_CC=cl
ac_cv_target=i686-pc-mingw32

## ----------------- ##
## Output variables. ##
## ----------------- ##

ac_ct_CC='cl'
ac_ct_CXX=''
AR=''
ARFLAGS=''
bindir='${exec_prefix}/bin'
build_alias=''
build_cpu='i686'
build_os='mingw32'
build_vendor='pc'
build='i686-pc-mingw32'
CC='cl'
CFLAGS=' /Gy /MD'
COMPILE_LINK_ENVVAR=''
CPP=''
CPPFLAGS=''
cross_buildroot=''
cross_compiling='no'
CXX='cl'
CXXFLAGS=' /Gy /MD'
DATA_PACKAGING_MODE=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
DEFS=''
docdir='${datarootdir}/doc/${PACKAGE}'
DOXYGEN=''
dvidir='${docdir}'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_DEBUG='0'
ENABLE_RELEASE='1'
ENABLE_RPATH=''
ENABLE_SHARED=''
ENABLE_STATIC=''
exec_prefix='NONE'
EXEEXT=''
EXTRAS_TRUE=''
GENCCODE_ASSEMBLY=''
GREP=''
HAVE_INT16_T=''
HAVE_INT32_T=''
HAVE_INT64_T=''
HAVE_INT8_T=''
HAVE_MMAP=''
HAVE_UINT16_T=''
HAVE_UINT32_T=''
HAVE_UINT64_T=''
HAVE_UINT8_T=''
host_alias=''
host_cpu='i686'
host_os='mingw32'
host_vendor='pc'
host='i686-pc-mingw32'
htmldir='${docdir}'
ICU_ECHO_C=''
ICU_ECHO_N='-n'
ICU_ECHO_T=''
ICU_USE_THREADS=''
ICUDATA_CHAR=''
ICUIO_TRUE=''
ICULIBSUFFIX=''
ICULIBSUFFIXCNAME=''
includedir='${prefix}/include'
infodir='${datarootdir}/info'
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
LAYOUT_TRUE=''
LDFLAGS=''
LIB_M=''
LIB_THREAD=''
LIB_VERSION_MAJOR='48'
LIB_VERSION='48.1.1'
LIBCFLAGS=''
LIBCXXFLAGS=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
LIBOBJS=''
LIBS=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
LTLIBOBJS=''
mandir='${datarootdir}/man'
OBJEXT=''
oldincludedir='/usr/include'
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PACKAGE='icu'
PATH_SEPARATOR=':'
pdfdir='${docdir}'
pkgicudatadir=''
platform_make_fragment_name=''
platform_make_fragment=''
platform=''
prefix='c:\dev2\icu'
program_transform_name='s,x,x,'
psdir='${docdir}'
RANLIB=''
SAMPLES_TRUE=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
SHELL='/bin/sh'
sysconfdir='${prefix}/etc'
target_alias=''
target_cpu='i686'
target_os='mingw32'
target_vendor='pc'
target='i686-pc-mingw32'
TESTS_TRUE=''
thepkgicudatadir=''
THREADS_TRUE=''
U_CHECK_DYLOAD=''
U_CHECK_GNUC_UTF16_STRING=''
U_CHECK_UTF16_STRING=''
U_DEFAULT_SHOW_DRAFT=''
U_DISABLE_RENAMING=''
U_ENABLE_DYLOAD=''
U_ENABLE_TRACING=''
U_HAVE_DIRENT_H=''
U_HAVE_GCC_ATOMICS=''
U_HAVE_INTTYPES_H=''
U_HAVE_LIB_SUFFIX=''
U_HAVE_NAMESPACE=''
U_HAVE_NL_LANGINFO_CODESET=''
U_HAVE_PLACEMENT_NEW=''
U_HAVE_POPEN=''
U_HAVE_STD_STRING=''
U_HAVE_TIMEZONE=''
U_HAVE_TZNAME=''
U_HAVE_TZSET=''
U_HAVE_WCHAR_H=''
U_HAVE_WCSCPY=''
U_INLINE=''
U_IOSTREAM_SOURCE=''
U_IS_BIG_ENDIAN=''
U_MAKE=''
U_NL_LANGINFO_CODESET=''
U_OVERRIDE_CXX_ALLOCATION=''
U_SIZEOF_WCHAR_T=''
U_TIMEZONE=''
U_TZNAME=''
U_TZSET=''
U_USE_GCC_VISIBILITY_ATTRIBUTE=''
U_USING_CYGWIN_MSVC=''
UCLN_NO_AUTO_CLEANUP=''
UNICODE_VERSION='6.0'
VERSION='4.8.1.1'

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77

**Comment by springmeyer** [comment]
windows is not supported by these scripts. instead I use: https://github.com/mapbox/windows-builds

**Comment by maraev** [comment]
Thanks!

2015-07-29 16:29 GMT+03:00 Dane Springmeyer <notifications@github.com>:

> windows is not supported by these scripts. instead I use:
> https://github.com/mapbox/windows-builds
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapnik/mapnik-packaging/issues/192#issuecomment-125952884>
> .
>



-- 
Best Regards!
Andrey Maraev
